- stage: deploy
  jobs:
  - deployment: DeployWeb
    displayName: deploy Web App
    pool:
      vmImage: 'Ubuntu-latest'
    # creates an environment if it doesn't exist
    environment: 'New_enviroment'
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo Hello world